version: '3.9'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_DB: pokemon_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: aspnet_app
    depends_on:
      - db
    ports:
      - "5001:5001"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: pokemon_app
      DB_USER: postgres
      DB_PASS: postgres
